import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.scss'
import {TitreH2, NavBar, Footer} from "@damchap/ui";
import clsx from "clsx";

const inter = Inter({ subsets: ['latin'] })

const navItems = [
    {
        link: '/',
        name: 'Home',
        icon: 'mdi:home'
    },
    {
        link: '/about',
        name: 'About',
        icon: 'mdi:account'
    },
    {
        link: '/projects',
        name: 'Projects',
        icon: 'mdi:folder'
    }
]

const About = () => {

    return (
        <>
            <Head>
                <title>Le blog | Damien chapart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <NavBar className={inter.className} navItems={navItems} />
            </header>
            <main className={styles.main}>
                <TitreH2 className={clsx(inter.className)}>Le blog</TitreH2>
                <section className={styles.section}>
                    <TitreH2 className={clsx(inter.className)}>📌 Mes articles</TitreH2>
                </section>
            </main>
            <Footer className={clsx(inter.className)} />
        </>
    )
};
export default About;