import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.scss'
import {Button, TitreH1, TitreH3, TitreH2, TitreH4, ArticleItem, NavBar, ProjectPromote, Footer, Project} from "@damchap/ui";
import clsx from "clsx";

// images
import chapart_damien from '/public/damien_chapart_full.png';

const inter = Inter({ subsets: ['latin'] })

const navItems = [
    {
        link: '/',
        name: 'Home',
        icon: 'mdi:home'
    },
    {
        link: '/about',
        name: 'About',
        icon: 'mdi:account'
    },
    {
        link: '/projects',
        name: 'Projects',
        icon: 'mdi:folder'
    }
]
const onclick = () => {
    console.log("test")
}
export default function About() {
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <NavBar className={inter.className} navItems={navItems} />
            </header>
            <main className={styles.main}>
                <section className={styles.section}>
                    <TitreH2 className={clsx(inter.className)}>🤔 Qui suis-je</TitreH2>
                    <div className={styles.content}>
                        <div>
                            <Image src={chapart_damien}
                                   alt={"photo de damien chapart"}
                                   width={284}
                                   height={486}
                            />
                        </div>
                        <div>
                            <TitreH3 className={clsx(inter.className, styles.TitreContent)}>Damien Chapart</TitreH3>
                            <TitreH4 className={clsx(inter.className)}>Etudiant en licence pro et développeur full stack</TitreH4>
                            <p className={clsx(inter.className, styles.info)}>
                                Bonjour et bienvenue, je me présente Damien Chapart, apprenti développeur web, passionné par les nouvelles technologies et leurs facultés à améliorer la productivité des entreprises.
                                <br/>
                                <br/>
                                Je réalise depuis plusieurs années, différents projets personnels ou professionnels dans le domaine de l’informatique, plus particulièrement dans le développement web ainsi que l’hébergement.
                                <br/>
                                <br/>
                                J’ai commencé par un baccalauréat STI2D (Sciences et Technologies de l’Industrie et du Développement Durable) au lycée Le Likès La Salle. Par la suite, je me suis orienté vers un BTS (Brevet de Technicien Supérieur) SIO (Service Informatique aux Organisations) option SLAM (Solution logiciel et Application Métier) à Saint Louis Châteaulin où j’ai pu acquérir de nombreuses compétences et connaissances. Après ces deux années d’études supérieures, j’ai eu une révélation pour le domaine du web et du design. Depuis, je m’implique activement dans ces domaines, ce qui m’a conduit à poursuivre ma formation en licence professionnelle à la digital school Brest

                            </p>
                            <Image src={"https://ghchart.rshah.org/0099F2/damchap"}
                                   alt={"damchap GitHub contributions graph"}
                                      width={782}
                                        height={125}

                            />
                        </div>
                    </div>
                </section>

            </main>
            <Footer className={clsx(inter.className)} />
        </>
    )
}
