import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import {Button, TitreH1} from "@damchap/ui";
import {NavBar} from "@damchap/ui/src/Molecules/NavBar/NavBar";
import clsx from "clsx";
import {TitreH2} from "@damchap/ui/src/Atoms/TitreH2/TitreH2";
import {TitreH3} from "@damchap/ui/src/Atoms/TitreH3/TitreH3";
import {TitreH4} from "@damchap/ui/src/Atoms/TitreH1/TitreH4/TitreH4";

// images
import chapart_damien from '/public/chapart_damien.png';
import logo_clevguard from '/public/logo_clevguard.png';
import Link from "next/link";
import {ArcticleItem} from "@damchap/ui/src/Molecules/ArcticleItem/ArcticleItem";

const inter = Inter({ subsets: ['latin'] })
class techno {
    constructor(public name: string, public icon: string) {
    }
}
const navItems = [
    {
        link: '/',
        name: 'Home',
        icon: 'mdi:home'
    },
    {
        link: '/about',
        name: 'About',
        icon: 'mdi:account'
    },
    {
        link: '/projects',
        name: 'Projects',
        icon: 'mdi:folder'
    }
]
const onclick = () => {
    console.log("test")
}
export default function Home() {
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <NavBar className={inter.className} navItems={navItems} />
      </header>
      <main className={styles.main}>
          <span className={clsx(inter.className, styles.HelloWorld)}>Hello! 👋 Moi c’est</span>
          <TitreH1 className={clsx(styles.titreH1, inter.className)}>
              <span className={styles.titreH1span} >Damien</span> Chapart
          </TitreH1>
          <h2 className={clsx(inter.className, styles.BaseLine)}>Développeur Full stack.</h2>
            <p className={clsx(inter.className, styles.Description)}>Je suis un développeur web full stack, spécialisé dans le développement d'applications web et mobiles.</p>
          <div className={clsx(styles.HeaderButton)}>
              <Button onClick={onclick} className={clsx(inter.className)} color={"#2181FA"}> ME CONTACTER</Button>
              <Button onClick={onclick} className={clsx(inter.className)} color={"#2181FA"} outline={true} icon={"mdi:github"}> Github</Button>
          </div>
          <section className={styles.section}>
              <TitreH2 className={clsx(inter.className)}>🤖 Qui suis-je</TitreH2>
              <div className={styles.content}>
                  <div>
                      <Image src={chapart_damien}
                             alt="Picture of the author"
                             width={241}
                             height={276}
                             priority={true}
                      />
                  </div>
                  <div>
                      <TitreH3 className={clsx(inter.className, styles.TitreContent)}>Damien Chapart</TitreH3>
                      <TitreH4 className={clsx(inter.className)}>Etudiant en licence pro et développeur full stack</TitreH4>
                      <p className={clsx(inter.className, styles.info)}>
                          Bonjour et bienvenue, je un développeur junior, passionné par les nouvelles technologies et leurs facultés à améliorer la productivité des entreprises.
                          <br/>
                          <br/>
                          Je réalise depuis plusieurs années, différents projets personnels ou professionnels dans le domaine de l’informatique, plus particulièrement dans le développement web ainsi que l’hébergement.
                      </p>
                      <Button onClick={onclick} className={clsx(inter.className)} color={"#2181FA"} outline={true} > En savoir Plus</Button>
                  </div>
              </div>
          </section>
          <section className={styles.section}>
              <TitreH2 className={clsx(inter.className)}>📘 Projet en avant</TitreH2>
              <div className={styles.content}>
                  <div>
                      <Image src={logo_clevguard}
                             alt="Picture of the author"
                             width={414}
                             height={230}
                             priority={true}
                      />
                  </div>
                  <div>
                      <TitreH3 className={clsx(inter.className, styles.TitreContent)}>Assistant Clevguard</TitreH3>
                      <time className={clsx(inter.className, styles.time)}>2019 - 2020</time>
                      <p className={clsx(inter.className, styles.info)}>
                          Clevguard est un projet de fin d’année de terminale STI2D (Sciences et Technologies de l’Industrie et du Développement Durable) option SIN (Système d’information et numérique).
                          Le projet Clevguard est divisé en plusieurs composantes, des boîtiers de capteurs divers ainsi qu’une progressive Web App permettant une visualisation des données des capteurs.
                      </p>
                      <Link href="/" className={clsx(inter.className, styles.Link)}>En savoir plus</Link>
                  </div>
              </div>
          </section>
          <section className={styles.section}>
              <TitreH2 className={clsx(inter.className)}>🖋️Article récents</TitreH2>
              <div className={styles.content}>
                <ArcticleItem className={clsx(inter.className, styles.article)}
                              Image={{src:"/iconArticle/Congratulations.svg", alt:"test"}}
                              Title={"Allez ç’est (re)parti pour de nouvelle aventure ! 💥"}
                              Date={new Date(2023, 1, 1)}
                              Description={"pnpm, next.js, react, versel ou bien vue, nuxt3, netlify. Quelle de ce technologie j’utilise aujourd’hui pour développer des projects cumulent une partie front et back avec une api Rest ou"}
                              Technologies={new Array<techno>(new techno("React", "mdi:react"), new techno("Next.js", "mdi:nextjs"))}/>
                  <ArcticleItem className={clsx(inter.className, styles.article)}
                                Image={{src:"/iconArticle/Congratulations.svg", alt:"test"}}
                                Title={"Allez ç’est (re)parti pour de nouvelle aventure ! 💥"}
                                Date={new Date(2023, 1, 1)}
                                Description={"pnpm, next.js, react, versel ou bien vue, nuxt3, netlify. Quelle de ce technologie j’utilise aujourd’hui pour développer des projects cumulent une partie front et back avec une api Rest ou"}
                                Technologies={new Array<techno>(new techno("React", "mdi:react"), new techno("Next.js", "mdi:nextjs"))}/>
                  <ArcticleItem className={clsx(inter.className, styles.article)}
                                Image={{src:"/iconArticle/Congratulations.svg", alt:"test"}}
                                Title={"Allez ç’est (re)parti pour de nouvelle aventure ! 💥"}
                                Date={new Date(2023, 1, 1)}
                                Description={"pnpm, next.js, react, versel ou bien vue, nuxt3, netlify. Quelle de ce technologie j’utilise aujourd’hui pour développer des projects cumulent une partie front et back avec une api Rest ou"}
                                Technologies={new Array<techno>(new techno("React", "mdi:react"), new techno("Next.js", "mdi:nextjs"))}/>
              </div>
          </section>
      </main>
    </>
  )
}
