import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.scss'
import {Button, TitreH1, TitreH3, TitreH2, TitreH4, ArticleItem, NavBar, ProjectPromote, Footer, Project, BlockDescription} from "@damchap/ui";
import clsx from "clsx";

// images
import chapart_damien from '/public/damien_chapart_full.png';

const inter = Inter({ subsets: ['latin'] })

const navItems = [
    {
        link: '/',
        name: 'Home',
        icon: 'mdi:home'
    },
    {
        link: '/about',
        name: 'About',
        icon: 'mdi:account'
    },
    {
        link: '/projects',
        name: 'Projects',
        icon: 'mdi:folder'
    }
]
const onclick = () => {
    console.log("test")
}
export default function About() {
    return (
        <>
            <Head>
                <title>Les Projets | Damien chapart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <TitreH2 className={clsx(inter.className)}>Les projects</TitreH2>
                <section className={styles.section}>
                    <TitreH2 className={clsx(inter.className)}>📌 Quelque project</TitreH2>
                    <div className={clsx(styles.row)}>
                        <Project className={clsx(inter.className)} UrlImage={"/logo_clevguard.png"} Technologies={["logos:c-plusplus", "logos:arduino", "logos:raspberry-pi","logos:php", "vscode-icons:file-type-composer"]} />
                        <Project  className={clsx(inter.className)} UrlImage={"/logo_clevguard.png"} Technologies={["logos:c-plusplus", "logos:arduino", "logos:raspberry-pi","logos:php", "vscode-icons:file-type-composer"]} />
                    </div>
                    <div className={clsx(styles.row)}>
                        <Project className={clsx(inter.className)} UrlImage={"/logo_clevguard.png"} Technologies={["logos:c-plusplus", "logos:arduino", "logos:raspberry-pi","logos:php", "vscode-icons:file-type-composer"]} />
                        <Project  className={clsx(inter.className)} UrlImage={"/logo_clevguard.png"} Technologies={["logos:c-plusplus", "logos:arduino", "logos:raspberry-pi","logos:php", "vscode-icons:file-type-composer"]} />

                    </div>

                </section>
            </main>
        </>
    )
}
